name: Auth
version: '${project.version}'
main: simpleauth.auth.Auth
api-version: 1.19
authors: [ santaxxm ]

commands:
  register:
    permission: auth.register
    permission-message: You do not have permission!
    usage: /register <nickname> <password>
  login:
    permission: auth.login
    permission-message: You do not have permission!
    usage: /login <nickname> <password>
  ForceLoginCommand:
    permission: auth.forcelogin
    permission-message: You do not have permission!
    usage: /forcelogin <nickname>

permissions:
  auth.forcelogin:
    description: Allow to force login players
    default: op
  auth.login:
    description: Allow to force login players
    default: true
    auth.register:
      description: Allow to force login players
      default: true